In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('population.csv')
data

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
0,1,Uttar Pradesh,Lucknow,"19,98,12,341",16.50,"10,44,80,510","9,53,31,831",912,67.68,"15,51,11,022","4,44,70,455","2,40,928",828,20.10%
1,2,Maharashtra,Mumbai,"11,23,74,333",9.28,"5,82,43,056","5,41,31,277",929,82.34,"6,15,45,441","5,08,27,531","3,07,713",365,16.00%
2,3,Bihar,Patna,"10,40,99,452",8.60,"5,42,78,157","4,98,21,295",918,61.80,"9,20,75,028","1,17,29,609","94,163","1,102",25.10%
3,4,West Bengal,Kolkata,"9,12,76,115",7.54,"4,68,09,027","4,44,67,088",950,76.26,"6,22,13,676","2,91,34,060","88,752","1,030",13.90%
4,5,Andhra Pradesh,Hyderabad,"8,45,80,777",6.99,"4,24,42,146","4,21,38,631",993,67.02,"5,63,61,702","2,82,19,075","2,75,045",308,10.98%
5,6,Madhya Pradesh,Bhopal,"7,26,26,809",6.00,"3,76,12,306","3,50,14,503",931,69.32,"5,25,37,899","2,00,59,666","3,08,245",236,20.30%
6,7,Tamil Nadu,Chennai,"7,21,47,030",5.96,"3,61,37,975","3,60,09,055",996,80.09,"3,71,89,229","3,49,49,729","1,30,058",555,15.60%
7,8,Rajasthan,Jaipur,"6,85,48,437",5.66,"3,55,50,997","3,29,97,440",928,66.11,"5,15,40,236","1,70,80,776","3,42,239",201,21.40%
8,9,Karnataka,Bengaluru,"6,10,95,297",5.05,"3,09,66,657","3,01,28,640",973,75.36,"3,75,52,529","2,35,78,175","1,91,791",319,15.70%
9,10,Gujarat,Gandhinagar,"6,04,39,692",4.99,"3,14,91,260","2,89,48,432",919,78.03,"3,46,70,817","2,57,12,811","1,96,024",308,19.20%
10,11,Odisha,Bhubaneshwar,"4,19,74,218",3.47,"2,12,12,136","2,07,62,082",979,72.87,"3,49,51,234","69,96,124","1,55,707",269,14.00%
11,12,Kerala,Thiruvananthapuram,"3,34,06,061",2.76,"1,60,27,412","1,73,78,649","1,084",94.00,"1,74,45,506","1,59,32,171","38,863",859,4.90%
12,13,Jharkhand,Ranchi,"3,29,88,134",2.72,"1,69,30,315","1,60,57,819",948,66.41,"2,50,36,946","79,29,292","79,714",414,22.30%
13,14,Assam,Dispur,"3,12,05,576",2.58,"1,59,39,443","1,52,66,133",958,72.19,"2,67,80,526","43,88,756","78,438",397,16.90%
14,15,Punjab,Chandigarh,"2,77,43,338",2.29,"1,46,39,465","1,31,03,873",895,75.84,"1,73,16,800","1,03,87,436","50,362",550,13.70%
15,16,Chhattisgarh,Raipur,"2,55,45,198",2.11,"1,28,32,895","1,27,12,303",991,70.28,"1,96,03,658","59,36,538","1,35,191",189,22.60%
16,17,Haryana,Chandigarh,"2,53,51,462",2.09,"1,34,94,734","1,18,56,728",879,75.55,"1,65,31,493","88,21,588","44,212",573,19.90%
17,18,Delhi,Delhi,"1,67,87,941",1.39,"88,87,326","78,00,615",868,86.21,"9,44,727","1,29,05,780","1,484","11,297",21%
18,19,Jammu and Kashmir,Jammu and Kashmir,"1,25,41,302",1.04,"66,40,662","59,00,640",889,67.16,"91,34,820","34,14,106","2,22,236",56,23.70%
19,20,Uttarakhand,Dehradun,"1,00,86,292",0.83,"51,37,773","49,48,519",963,79.63,"70,25,583","30,91,169","53,483",189,19.20%
20,21,Himachal Pradesh,Shimla,"68,64,602",0.57,"34,81,873","33,82,729",972,82.80,"61,67,805","6,88,704","55,673",123,12.80%
21,22,Tripura,Agartala,"36,73,917",0.30,"18,74,376","17,99,541",960,87.22,"27,10,051","9,60,981","10,486",350,14.70%
22,23,Meghalaya,Shillong,"29,66,889",0.25,"14,91,832","14,75,057",989,74.43,"23,68,971","5,95,036","22,429",132,27.80%
23,24,Manipur,Imphal,"27,21,756",0.21,"12,90,171","12,80,219",992,79.21,"18,99,624","8,22,132","22,327",122,18.70%
24,25,Nagaland,Kohima,"19,78,502",0.16,"10,24,649","9,53,853",931,79.55,"14,06,861","5,73,741","16,579",119,0.50%
25,26,Goa,Panaji,"14,58,545",0.12,"7,39,140","7,19,405",973,88.70,"5,51,414","9,06,309","3,702",394,8.20%
26,27,Arunachal Pradesh,Itanagar,"13,83,727",0.11,"7,13,912","6,69,815",938,65.38,"10,69,165","3,13,446","83,743",17,25.90%
27,28,Puducherry,Pondicherry,"12,47,953",0.10,"6,12,511","6,35,442","1,037",85.85,"3,94,341","8,50,123",479,"2,598",27.70%
28,29,Mizoram,Aizawl,"10,97,206",0.09,"5,55,339","5,41,867",976,91.33,"5,29,037","5,61,997","21,081",52,22.80%
29,30,Chandigarh,Chandigarh,"10,55,450",0.09,"5,80,663","4,74,787",818,86.05,"29,004","10,25,682",114,"9,252",17.10%
30,31,Sikkim,Gangtok,"6,10,577",0.05,"3,23,070","2,87,507",890,81.42,"4,55,962","1,51,726","7,096",86,12.40%
31,32,Andaman and Nicobar Islands,Port Blair,"3,80,581",0.03,"2,02,871","1,77,710",876,86.63,"2,44,411","1,35,533","8,249",46,6.70%
32,33,Dadra and Nagar Haveli,Silvassa,"3,43,709",0.03,"1,93,760","1,49,949",774,76.24,"1,83,024","1,59,829",491,698,55.50%
33,34,Daman and Diu,Daman,"2,43,247",0.02,"1,50,301","92,946",618,87.10,"60,331","1,82,580",112,"2,169",53.50%
34,35,Lakshadweep,Kavaratti,"64,473",0.01,"33,123","31,350",946,91.85,"14,121","50,308",32,"2,013",6.20%

In [3]:
data[['Rank','State']]

    Rank                        State
0      1                Uttar Pradesh
1      2                  Maharashtra
2      3                        Bihar
3      4                  West Bengal
4      5               Andhra Pradesh
5      6               Madhya Pradesh
6      7                   Tamil Nadu
7      8                    Rajasthan
8      9                    Karnataka
9     10                      Gujarat
10    11                       Odisha
11    12                       Kerala
12    13                    Jharkhand
13    14                        Assam
14    15                       Punjab
15    16                 Chhattisgarh
16    17                      Haryana
17    18                        Delhi
18    19            Jammu and Kashmir
19    20                  Uttarakhand
20    21             Himachal Pradesh
21    22                      Tripura
22    23                    Meghalaya
23    24                      Manipur
24    25                     Nagaland
25    26                          Goa
26    27            Arunachal Pradesh
27    28                   Puducherry
28    29                      Mizoram
29    30                   Chandigarh
30    31                       Sikkim
31    32  Andaman and Nicobar Islands
32    33       Dadra and Nagar Haveli
33    34                Daman and Diu
34    35                  Lakshadweep

In [4]:
data[['State','Population']]

                          State    Population
0                 Uttar Pradesh  19,98,12,341
1                   Maharashtra  11,23,74,333
2                         Bihar  10,40,99,452
3                   West Bengal   9,12,76,115
4                Andhra Pradesh   8,45,80,777
5                Madhya Pradesh   7,26,26,809
6                    Tamil Nadu   7,21,47,030
7                     Rajasthan   6,85,48,437
8                     Karnataka   6,10,95,297
9                       Gujarat   6,04,39,692
10                       Odisha   4,19,74,218
11                       Kerala   3,34,06,061
12                    Jharkhand   3,29,88,134
13                        Assam   3,12,05,576
14                       Punjab   2,77,43,338
15                 Chhattisgarh   2,55,45,198
16                      Haryana   2,53,51,462
17                        Delhi   1,67,87,941
18            Jammu and Kashmir   1,25,41,302
19                  Uttarakhand   1,00,86,292
20             Himachal Pradesh     68,64,602
21                      Tripura     36,73,917
22                    Meghalaya     29,66,889
23                      Manipur     27,21,756
24                     Nagaland     19,78,502
25                          Goa     14,58,545
26            Arunachal Pradesh     13,83,727
27                   Puducherry     12,47,953
28                      Mizoram     10,97,206
29                   Chandigarh     10,55,450
30                       Sikkim      6,10,577
31  Andaman and Nicobar Islands      3,80,581
32       Dadra and Nagar Haveli      3,43,709
33                Daman and Diu      2,43,247
34                  Lakshadweep        64,473

In [11]:
data[['State','Rural Population']]

                          State Rural Population
0                 Uttar Pradesh     15,51,11,022
1                   Maharashtra      6,15,45,441
2                         Bihar      9,20,75,028
3                   West Bengal      6,22,13,676
4                Andhra Pradesh      5,63,61,702
5                Madhya Pradesh      5,25,37,899
6                    Tamil Nadu      3,71,89,229
7                     Rajasthan      5,15,40,236
8                     Karnataka      3,75,52,529
9                       Gujarat      3,46,70,817
10                       Odisha      3,49,51,234
11                       Kerala      1,74,45,506
12                    Jharkhand      2,50,36,946
13                        Assam      2,67,80,526
14                       Punjab      1,73,16,800
15                 Chhattisgarh      1,96,03,658
16                      Haryana      1,65,31,493
17                        Delhi         9,44,727
18            Jammu and Kashmir        91,34,820
19                  Uttarakhand        70,25,583
20             Himachal Pradesh        61,67,805
21                      Tripura        27,10,051
22                    Meghalaya        23,68,971
23                      Manipur        18,99,624
24                     Nagaland        14,06,861
25                          Goa         5,51,414
26            Arunachal Pradesh        10,69,165
27                   Puducherry         3,94,341
28                      Mizoram         5,29,037
29                   Chandigarh           29,004
30                       Sikkim         4,55,962
31  Andaman and Nicobar Islands         2,44,411
32       Dadra and Nagar Haveli         1,83,024
33                Daman and Diu           60,331
34                  Lakshadweep           14,121

In [14]:
#loc = index name
data.loc[data.State=='Goa']

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
25,26,Goa,Panaji,"14,58,545",0.12,"7,39,140","7,19,405",973,88.7,"5,51,414","9,06,309","3,702",394,8.20%

In [15]:
data.loc[data.State=='Maharashtra']

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
1,2,Maharashtra,Mumbai,"11,23,74,333",9.28,"5,82,43,056","5,41,31,277",929,82.34,"6,15,45,441","5,08,27,531","3,07,713",365,16.00%

In [16]:
data.loc[data.Capital=='Jaipur']

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
7,8,Rajasthan,Jaipur,"6,85,48,437",5.66,"3,55,50,997","3,29,97,440",928,66.11,"5,15,40,236","1,70,80,776","3,42,239",201,21.40%

In [7]:
data.loc[data.Rank==5]

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
4,5,Andhra Pradesh,Hyderabad,"8,45,80,777",6.99,"4,24,42,146","4,21,38,631",993,67.02,"5,63,61,702","2,82,19,075","2,75,045",308,10.98%

In [20]:
data['Population'] = data['Population'].astype(str)

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rank                   35 non-null     int64
 1   State                  35 non-null     object
 2   Capital                35 non-null     object
 3   Population             35 non-null     int64
 4   % of Total Population  35 non-null     float64
 5   Males                  35 non-null     int64
 6   Females                35 non-null     int64
 7   Gender Ratio           35 non-null     int64
 8   Literacy Rate (%)      35 non-null     float64
 9   Rural Population       35 non-null     int64
 10  Urban Population       35 non-null     object
 11  Area (km*km)           35 non-null     object
 12  Density (1/km*km)      35 non-null     object
 13  Decadal Growth (%)     35 non-null     object
dtypes: float64(2), int64(6), object(6)
memory usage: 4.0+ KB

In [23]:
data['Population'] = data['Population'].str.replace(',','')

In [25]:
data['Population'] = pd.to_numeric(data['Population'])

In [26]:
data.loc[(data.State=='Tamil Nadu') & (data.Population>=500000)]

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
6,7,Tamil Nadu,Chennai,72147030,5.96,"3,61,37,975","3,60,09,055",996,80.09,"3,71,89,229","3,49,49,729","1,30,058",555,15.60%

In [28]:
data['Males'] = data['Males'].str.replace(',','')

In [29]:
data['Males'] = pd.to_numeric(data['Males'])

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rank                   35 non-null     int64
 1   State                  35 non-null     object
 2   Capital                35 non-null     object
 3   Population             35 non-null     int64
 4   % of Total Population  35 non-null     float64
 5   Males                  35 non-null     int64
 6   Females                35 non-null     object
 7   Gender Ratio           35 non-null     object
 8   Literacy Rate (%)      35 non-null     float64
 9   Rural Population       35 non-null     object
 10  Urban Population       35 non-null     object
 11  Area (km*km)           35 non-null     object
 12  Density (1/km*km)      35 non-null     object
 13  Decadal Growth (%)     35 non-null     object
dtypes: float64(2), int64(3), object(9)
memory usage: 4.0+ KB

In [51]:
data.loc[(data.Males>30966657)]

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
0,1,Uttar Pradesh,Lucknow,199812341,16.50,104480510,95331831,912,67.68,155111022,"4,44,70,455","2,40,928",828,20.10%
1,2,Maharashtra,Mumbai,112374333,9.28,58243056,54131277,929,82.34,61545441,"5,08,27,531","3,07,713",365,16.00%
2,3,Bihar,Patna,104099452,8.60,54278157,49821295,918,61.80,92075028,"1,17,29,609","94,163","1,102",25.10%
3,4,West Bengal,Kolkata,91276115,7.54,46809027,44467088,950,76.26,62213676,"2,91,34,060","88,752","1,030",13.90%
4,5,Andhra Pradesh,Hyderabad,84580777,6.99,42442146,42138631,993,67.02,56361702,"2,82,19,075","2,75,045",308,10.98%
5,6,Madhya Pradesh,Bhopal,72626809,6.00,37612306,35014503,931,69.32,52537899,"2,00,59,666","3,08,245",236,20.30%
6,7,Tamil Nadu,Chennai,72147030,5.96,36137975,36009055,996,80.09,37189229,"3,49,49,729","1,30,058",555,15.60%
7,8,Rajasthan,Jaipur,68548437,5.66,35550997,32997440,928,66.11,51540236,"1,70,80,776","3,42,239",201,21.40%
9,10,Gujarat,Gandhinagar,60439692,4.99,31491260,28948432,919,78.03,34670817,"2,57,12,811","1,96,024",308,19.20%

In [36]:
data['Females'] = data['Females'].str.replace(',','')

In [37]:
data['Females'] = pd.to_numeric(data['Females'])

In [41]:
data.loc[(data['Females']>177710)]

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
0,1,Uttar Pradesh,Lucknow,199812341,16.50,104480510,95331831,912,67.68,"15,51,11,022","4,44,70,455","2,40,928",828,20.10%
1,2,Maharashtra,Mumbai,112374333,9.28,58243056,54131277,929,82.34,"6,15,45,441","5,08,27,531","3,07,713",365,16.00%
2,3,Bihar,Patna,104099452,8.60,54278157,49821295,918,61.80,"9,20,75,028","1,17,29,609","94,163","1,102",25.10%
3,4,West Bengal,Kolkata,91276115,7.54,46809027,44467088,950,76.26,"6,22,13,676","2,91,34,060","88,752","1,030",13.90%
4,5,Andhra Pradesh,Hyderabad,84580777,6.99,42442146,42138631,993,67.02,"5,63,61,702","2,82,19,075","2,75,045",308,10.98%
5,6,Madhya Pradesh,Bhopal,72626809,6.00,37612306,35014503,931,69.32,"5,25,37,899","2,00,59,666","3,08,245",236,20.30%
6,7,Tamil Nadu,Chennai,72147030,5.96,36137975,36009055,996,80.09,"3,71,89,229","3,49,49,729","1,30,058",555,15.60%
7,8,Rajasthan,Jaipur,68548437,5.66,35550997,32997440,928,66.11,"5,15,40,236","1,70,80,776","3,42,239",201,21.40%
8,9,Karnataka,Bengaluru,61095297,5.05,30966657,30128640,973,75.36,"3,75,52,529","2,35,78,175","1,91,791",319,15.70%
9,10,Gujarat,Gandhinagar,60439692,4.99,31491260,28948432,919,78.03,"3,46,70,817","2,57,12,811","1,96,024",308,19.20%
10,11,Odisha,Bhubaneshwar,41974218,3.47,21212136,20762082,979,72.87,"3,49,51,234","69,96,124","1,55,707",269,14.00%
11,12,Kerala,Thiruvananthapuram,33406061,2.76,16027412,17378649,"1,084",94.00,"1,74,45,506","1,59,32,171","38,863",859,4.90%
12,13,Jharkhand,Ranchi,32988134,2.72,16930315,16057819,948,66.41,"2,50,36,946","79,29,292","79,714",414,22.30%
13,14,Assam,Dispur,31205576,2.58,15939443,15266133,958,72.19,"2,67,80,526","43,88,756","78,438",397,16.90%
14,15,Punjab,Chandigarh,27743338,2.29,14639465,13103873,895,75.84,"1,73,16,800","1,03,87,436","50,362",550,13.70%
15,16,Chhattisgarh,Raipur,25545198,2.11,12832895,12712303,991,70.28,"1,96,03,658","59,36,538","1,35,191",189,22.60%
16,17,Haryana,Chandigarh,25351462,2.09,13494734,11856728,879,75.55,"1,65,31,493","88,21,588","44,212",573,19.90%
17,18,Delhi,Delhi,16787941,1.39,8887326,7800615,868,86.21,"9,44,727","1,29,05,780","1,484","11,297",21%
18,19,Jammu and Kashmir,Jammu and Kashmir,12541302,1.04,6640662,5900640,889,67.16,"91,34,820","34,14,106","2,22,236",56,23.70%
19,20,Uttarakhand,Dehradun,10086292,0.83,5137773,4948519,963,79.63,"70,25,583","30,91,169","53,483",189,19.20%
20,21,Himachal Pradesh,Shimla,6864602,0.57,3481873,3382729,972,82.80,"61,67,805","6,88,704","55,673",123,12.80%
21,22,Tripura,Agartala,3673917,0.30,1874376,1799541,960,87.22,"27,10,051","9,60,981","10,486",350,14.70%
22,23,Meghalaya,Shillong,2966889,0.25,1491832,1475057,989,74.43,"23,68,971","5,95,036","22,429",132,27.80%
23,24,Manipur,Imphal,2721756,0.21,1290171,1280219,992,79.21,"18,99,624","8,22,132","22,327",122,18.70%
24,25,Nagaland,Kohima,1978502,0.16,1024649,953853,931,79.55,"14,06,861","5,73,741","16,579",119,0.50%
25,26,Goa,Panaji,1458545,0.12,739140,719405,973,88.70,"5,51,414","9,06,309","3,702",394,8.20%
26,27,Arunachal Pradesh,Itanagar,1383727,0.11,713912,669815,938,65.38,"10,69,165","3,13,446","83,743",17,25.90%
27,28,Puducherry,Pondicherry,1247953,0.10,612511,635442,"1,037",85.85,"3,94,341","8,50,123",479,"2,598",27.70%
28,29,Mizoram,Aizawl,1097206,0.09,555339,541867,976,91.33,"5,29,037","5,61,997","21,081",52,22.80%
29,30,Chandigarh,Chandigarh,1055450,0.09,580663,474787,818,86.05,"29,004","10,25,682",114,"9,252",17.10%
30,31,Sikkim,Gangtok,610577,0.05,323070,287507,890,81.42,"4,55,962","1,51,726","7,096",86,12.40%

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rank                   35 non-null     int64
 1   State                  35 non-null     object
 2   Capital                35 non-null     object
 3   Population             35 non-null     int64
 4   % of Total Population  35 non-null     float64
 5   Males                  35 non-null     int64
 6   Females                35 non-null     int64
 7   Gender Ratio           35 non-null     object
 8   Literacy Rate (%)      35 non-null     float64
 9   Rural Population       35 non-null     object
 10  Urban Population       35 non-null     object
 11  Area (km*km)           35 non-null     object
 12  Density (1/km*km)      35 non-null     object
 13  Decadal Growth (%)     35 non-null     object
dtypes: float64(2), int64(4), object(8)
memory usage: 4.0+ KB

In [44]:
data['Gender Ratio'] = data['Gender Ratio'].str.replace(',','')
data['Gender Ratio'] = pd.to_numeric(data['Gender Ratio'])

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rank                   35 non-null     int64
 1   State                  35 non-null     object
 2   Capital                35 non-null     object
 3   Population             35 non-null     int64
 4   % of Total Population  35 non-null     float64
 5   Males                  35 non-null     int64
 6   Females                35 non-null     int64
 7   Gender Ratio           35 non-null     int64
 8   Literacy Rate (%)      35 non-null     float64
 9   Rural Population       35 non-null     object
 10  Urban Population       35 non-null     object
 11  Area (km*km)           35 non-null     object
 12  Density (1/km*km)      35 non-null     object
 13  Decadal Growth (%)     35 non-null     object
dtypes: float64(2), int64(5), object(7)
memory usage: 4.0+ KB

In [46]:
data['Rural Population'] = data['Rural Population'].str.replace(',','')
data['Rural Population'] = pd.to_numeric(data['Rural Population'])

In [48]:
data.loc[(data['Rural Population']>=56361702)]

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
0,1,Uttar Pradesh,Lucknow,199812341,16.50,104480510,95331831,912,67.68,155111022,"4,44,70,455","2,40,928",828,20.10%
1,2,Maharashtra,Mumbai,112374333,9.28,58243056,54131277,929,82.34,61545441,"5,08,27,531","3,07,713",365,16.00%
2,3,Bihar,Patna,104099452,8.60,54278157,49821295,918,61.80,92075028,"1,17,29,609","94,163","1,102",25.10%
3,4,West Bengal,Kolkata,91276115,7.54,46809027,44467088,950,76.26,62213676,"2,91,34,060","88,752","1,030",13.90%
4,5,Andhra Pradesh,Hyderabad,84580777,6.99,42442146,42138631,993,67.02,56361702,"2,82,19,075","2,75,045",308,10.98%

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rank                   35 non-null     int64
 1   State                  35 non-null     object
 2   Capital                35 non-null     object
 3   Population             35 non-null     int64
 4   % of Total Population  35 non-null     float64
 5   Males                  35 non-null     int64
 6   Females                35 non-null     int64
 7   Gender Ratio           35 non-null     int64
 8   Literacy Rate (%)      35 non-null     float64
 9   Rural Population       35 non-null     int64
 10  Urban Population       35 non-null     object
 11  Area (km*km)           35 non-null     object
 12  Density (1/km*km)      35 non-null     object
 13  Decadal Growth (%)     35 non-null     object
dtypes: float64(2), int64(6), object(6)
memory usage: 4.0+ KB

In [55]:
data['Urban Population'] = data['Urban Population'].str.replace(',','')
data['Urban Population']= pd.to_numeric(data['Urban Population'])

SyntaxError: invalid syntax (3003908192.py, line 3)

In [56]:
data.loc[(data['Urban Population']>=25712811)]

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
0,1,Uttar Pradesh,Lucknow,199812341,16.50,104480510,95331831,912,67.68,155111022,44470455,"2,40,928",828,20.10%
1,2,Maharashtra,Mumbai,112374333,9.28,58243056,54131277,929,82.34,61545441,50827531,"3,07,713",365,16.00%
3,4,West Bengal,Kolkata,91276115,7.54,46809027,44467088,950,76.26,62213676,29134060,"88,752","1,030",13.90%
4,5,Andhra Pradesh,Hyderabad,84580777,6.99,42442146,42138631,993,67.02,56361702,28219075,"2,75,045",308,10.98%
6,7,Tamil Nadu,Chennai,72147030,5.96,36137975,36009055,996,80.09,37189229,34949729,"1,30,058",555,15.60%
9,10,Gujarat,Gandhinagar,60439692,4.99,31491260,28948432,919,78.03,34670817,25712811,"1,96,024",308,19.20%

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rank                   35 non-null     int64
 1   State                  35 non-null     object
 2   Capital                35 non-null     object
 3   Population             35 non-null     int64
 4   % of Total Population  35 non-null     float64
 5   Males                  35 non-null     int64
 6   Females                35 non-null     int64
 7   Gender Ratio           35 non-null     int64
 8   Literacy Rate (%)      35 non-null     float64
 9   Rural Population       35 non-null     int64
 10  Urban Population       35 non-null     int64
 11  Area (km*km)           35 non-null     object
 12  Density (1/km*km)      35 non-null     object
 13  Decadal Growth (%)     35 non-null     object
dtypes: float64(2), int64(7), object(5)
memory usage: 4.0+ KB

In [58]:
data['Area (km*km)'] = data['Area (km*km)'].str.replace(',','')
data['Area (km*km)'] = pd.to_numeric(data['Area (km*km)'])

In [59]:
data.loc[(data['Area (km*km)']>=196024)]

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
0,1,Uttar Pradesh,Lucknow,199812341,16.50,104480510,95331831,912,67.68,155111022,44470455,240928,828,20.10%
1,2,Maharashtra,Mumbai,112374333,9.28,58243056,54131277,929,82.34,61545441,50827531,307713,365,16.00%
4,5,Andhra Pradesh,Hyderabad,84580777,6.99,42442146,42138631,993,67.02,56361702,28219075,275045,308,10.98%
5,6,Madhya Pradesh,Bhopal,72626809,6.00,37612306,35014503,931,69.32,52537899,20059666,308245,236,20.30%
7,8,Rajasthan,Jaipur,68548437,5.66,35550997,32997440,928,66.11,51540236,17080776,342239,201,21.40%
9,10,Gujarat,Gandhinagar,60439692,4.99,31491260,28948432,919,78.03,34670817,25712811,196024,308,19.20%
18,19,Jammu and Kashmir,Jammu and Kashmir,12541302,1.04,6640662,5900640,889,67.16,9134820,3414106,222236,56,23.70%

In [60]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rank                   35 non-null     int64
 1   State                  35 non-null     object
 2   Capital                35 non-null     object
 3   Population             35 non-null     int64
 4   % of Total Population  35 non-null     float64
 5   Males                  35 non-null     int64
 6   Females                35 non-null     int64
 7   Gender Ratio           35 non-null     int64
 8   Literacy Rate (%)      35 non-null     float64
 9   Rural Population       35 non-null     int64
 10  Urban Population       35 non-null     int64
 11  Area (km*km)           35 non-null     int64
 12  Density (1/km*km)      35 non-null     object
 13  Decadal Growth (%)     35 non-null     object
dtypes: float64(2), int64(8), object(4)
memory usage: 4.0+ KB

In [63]:
data['Density (1/km*km)'] = data['Density (1/km*km)'].str.replace(',','')
data['Density (1/km*km)'] = pd.to_numeric(data['Density (1/km*km)'])

AttributeError: Can only use .str accessor with string values!

In [66]:
data.loc[(data['Density (1/km*km)']>308)]

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
0,1,Uttar Pradesh,Lucknow,199812341,16.50,104480510,95331831,912,67.68,155111022,44470455,240928,828,20.10%
1,2,Maharashtra,Mumbai,112374333,9.28,58243056,54131277,929,82.34,61545441,50827531,307713,365,16.00%
2,3,Bihar,Patna,104099452,8.60,54278157,49821295,918,61.80,92075028,11729609,94163,1102,25.10%
3,4,West Bengal,Kolkata,91276115,7.54,46809027,44467088,950,76.26,62213676,29134060,88752,1030,13.90%
6,7,Tamil Nadu,Chennai,72147030,5.96,36137975,36009055,996,80.09,37189229,34949729,130058,555,15.60%
8,9,Karnataka,Bengaluru,61095297,5.05,30966657,30128640,973,75.36,37552529,23578175,191791,319,15.70%
11,12,Kerala,Thiruvananthapuram,33406061,2.76,16027412,17378649,1084,94.00,17445506,15932171,38863,859,4.90%
12,13,Jharkhand,Ranchi,32988134,2.72,16930315,16057819,948,66.41,25036946,7929292,79714,414,22.30%
13,14,Assam,Dispur,31205576,2.58,15939443,15266133,958,72.19,26780526,4388756,78438,397,16.90%
14,15,Punjab,Chandigarh,27743338,2.29,14639465,13103873,895,75.84,17316800,10387436,50362,550,13.70%
16,17,Haryana,Chandigarh,25351462,2.09,13494734,11856728,879,75.55,16531493,8821588,44212,573,19.90%
17,18,Delhi,Delhi,16787941,1.39,8887326,7800615,868,86.21,944727,12905780,1484,11297,21%
21,22,Tripura,Agartala,3673917,0.30,1874376,1799541,960,87.22,2710051,960981,10486,350,14.70%
25,26,Goa,Panaji,1458545,0.12,739140,719405,973,88.70,551414,906309,3702,394,8.20%
27,28,Puducherry,Pondicherry,1247953,0.10,612511,635442,1037,85.85,394341,850123,479,2598,27.70%
29,30,Chandigarh,Chandigarh,1055450,0.09,580663,474787,818,86.05,29004,1025682,114,9252,17.10%
32,33,Dadra and Nagar Haveli,Silvassa,343709,0.03,193760,149949,774,76.24,183024,159829,491,698,55.50%
33,34,Daman and Diu,Daman,243247,0.02,150301,92946,618,87.10,60331,182580,112,2169,53.50%
34,35,Lakshadweep,Kavaratti,64473,0.01,33123,31350,946,91.85,14121,50308,32,2013,6.20%

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rank                   35 non-null     int64
 1   State                  35 non-null     object
 2   Capital                35 non-null     object
 3   Population             35 non-null     int64
 4   % of Total Population  35 non-null     float64
 5   Males                  35 non-null     int64
 6   Females                35 non-null     int64
 7   Gender Ratio           35 non-null     int64
 8   Literacy Rate (%)      35 non-null     float64
 9   Rural Population       35 non-null     int64
 10  Urban Population       35 non-null     int64
 11  Area (km*km)           35 non-null     int64
 12  Density (1/km*km)      35 non-null     int64
 13  Decadal Growth (%)     35 non-null     object
dtypes: float64(2), int64(9), object(3)
memory usage: 4.0+ KB

In [69]:
# data['Decadal Growth (%)'] = data['Decadal Growth (%)'].str.replace('%','')
# data['Decadal Growth (%)'] = pd.to_numeric(data['Decadal Growth (%)'])
data['Decadal Growth (%)'] = data['Decadal Growth (%)'].astype(float)

In [70]:
data.loc[(data['Decadal Growth (%)']>=25.10)]

,Rank,State,Capital,Population,% of Total Population,Males,Females,Gender Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
2,3,Bihar,Patna,104099452,8.60,54278157,49821295,918,61.80,92075028,11729609,94163,1102,25.1
22,23,Meghalaya,Shillong,2966889,0.25,1491832,1475057,989,74.43,2368971,595036,22429,132,27.8
26,27,Arunachal Pradesh,Itanagar,1383727,0.11,713912,669815,938,65.38,1069165,313446,83743,17,25.9
27,28,Puducherry,Pondicherry,1247953,0.10,612511,635442,1037,85.85,394341,850123,479,2598,27.7
32,33,Dadra and Nagar Haveli,Silvassa,343709,0.03,193760,149949,774,76.24,183024,159829,491,698,55.5
33,34,Daman and Diu,Daman,243247,0.02,150301,92946,618,87.10,60331,182580,112,2169,53.5